import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";
import ContextMenuDisabler from "../utils/ContextMenuDisabler";
import PrivyProvider from "../components/PrivyProvider";
import { Toaster } from "react-hot-toast";


const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kaiko",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={geologica.className}>
        <ContextMenuDisabler>
          <PrivyProvider>
            {children}
            <Toaster 
              position="top-center"
              toastOptions={{
                duration: 4000,
                style: {
                  background: '#363636',
                  color: '#fff',
                },
                success: {
                  duration: 3000,
                  iconTheme: {
                    primary: '#4ade80',
                    secondary: '#fff',
                  },
                },
                error: {
                  duration: 5000,
                  iconTheme: {
                    primary: '#ef4444',
                    secondary: '#fff',
                  },
                },
              }}
            />
          </PrivyProvider>
        </ContextMenuDisabler>
      </body>
    </html>
  );
}
