import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";
import ContextMenuWrapper from "@/components/ContextMenuWrapper"


const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kaiko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geologica.variable} antialiased`}
      >
        <ContextMenuWrapper>
          {children}
        </ContextMenuWrapper>
      </body>
    </html>
  );
}
